### ISSUE TITLE
Compatibility with AppliedE

### ISSUE THREAD

**Issue by border999** [tom5454/More-Immersive-Wires#14]
https://github.com/62832/AppliedE/issues/6

**Comment by SquidDev** [comment]
If possible @tom5454, it's better to avoid depending on CC's internals here. For instance, the usage of `ComponentAccess`/`PlatformHelper.createWiredElementAccess` can just be replaced by a normal capability lookup. [CC's README has some info](https://github.com/cc-tweaked/CC-Tweaked?tab=readme-ov-file#using) on how to just depend on the API so you don't accidentally pull in internal code.

**Comment by tom5454** [comment]
I'll replace that with a capability lookup, but I also have a custom modem:
https://github.com/tom5454/More-Immersive-Wires/blob/1.20/src/main/java/com/tom/morewires/compat/cc/CCModemConnectorBlockEntity.java
I don't see any API that would let me create a custom wired modem.
